/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MMCv211 {
  MediaPresentation?: Presentationtype;
  FileManifest?: FileManifesttype;
  MediaManifest?: MediaManifesttype;
  MediaPresentationManifest?: PresentationManifesttype;
  MediaManifestEdit?: MediaManifestEdittype;
  MediaInventory?: MediaInventorytype;
  FileDeleteManifest?: FileDeleteManifesttype;
  [k: string]: unknown;
}

export type PresentationtypeTrackMetadata = TrackMetadatatype & {
  [k: string]: unknown;
};

export type MarkerListtypeMarker = Markertype & {
  [k: string]: unknown;
};
export type AssociatedOrgtype = OrgNametype & {
  role?: string;
  roleCategory?: string;
  [k: string]: unknown;
};
export type PresentationTimelinetypeAudioTrackStart = Timecodetype & {
  audioTrackID?: string;
  [k: string]: unknown;
};
export type PresentationTimelinetypeVideoTrackStart = Timecodetype & {
  videoTrackID?: string;
  [k: string]: unknown;
};
export type PresentationTimelinetypeSubtitleTrackStart = Timecodetype & {
  subtitleTrackID?: string;
  [k: string]: unknown;
};
export type FileManifesttype = FileManifestInfotype & {
  [k: string]: unknown;
};
export type QCCategoryErrortypeAudio = QCErrorAudiotype & {
  [k: string]: unknown;
};
export type QCCategoryErrortypeVideo = QCErrorVideotype & {
  [k: string]: unknown;
};
export type QCCategoryErrortypeTimedText = QCErrorTimedTexttype & {
  [k: string]: unknown;
};
export type QCCategoryErrortypeArtwork = QCErrorArtworktype & {
  [k: string]: unknown;
};
export type QCCategoryErrortypeMetadata = QCErrorMetadatatype & {
  [k: string]: unknown;
};
export type StringVideoPicPixelAspect = "NTSC" | "PAL" | "square" | "other";
export type StringVideoPicProgressivescanOrder = "BFF" | "TFF" | "PPF";
export type ColorTypetype = "color" | "bandw" | "colorized" | "composite" | "unknown";
export type ManifestSourceLicensortype = OrgNametype & {
  /**
   * @minItems 0
   */
  ALID?: (
    | string
    | number
    | number
    | boolean
    | null
    | {
        [k: string]: unknown;
      }
    | unknown[]
  )[];
  [k: string]: unknown;
};
export type InventoryAudiotype = DigitalAssetAudioDatatype & {
  /**
   * @minItems 0
   */
  ContainerReference?: ContainerReferencetype[];
  AudioTrackID?: string;
  [k: string]: unknown;
};
export type InventoryVideotype = DigitalAssetVideoDatatype & {
  /**
   * @minItems 0
   */
  ContainerReference?: ContainerReferencetype[];
  VideoTrackID?: string;
  [k: string]: unknown;
};
export type InventorySubtitletype = DigitalAssetSubtitleDatatype & {
  /**
   * @minItems 0
   */
  ContainerReference?: ContainerReferencetype[];
  SubtitleTrackID?: string;
  [k: string]: unknown;
};
export type InventoryImagetype = DigitalAssetImageDatatype & {
  /**
   * @minItems 0
   */
  ContainerReference?: ContainerReferencetype[];
  VideoFrameTimecode?: InventoryImagetypeVideoFrameTimecode;
  InitialView?: DigitalAssetVideoPicture360Initialtype;
  ImageID?: string;
  [k: string]: unknown;
};
export type InventoryImagetypeVideoFrameTimecode = Timecodetype & {
  VideoTrackID?: string;
  [k: string]: unknown;
};
export type InventoryInteractivetype = DigitalAssetInteractiveDatatype & {
  /**
   * @minItems 0
   */
  ContainerReference?: ContainerReferencetype[];
  /**
   * @minItems 0
   */
  ManifestApp?: InventoryMediaManifesttype[];
  PictureID?: string;
  InteractiveTrackID?: string;
  [k: string]: unknown;
};
export type PlayableSequenceListtypePlayableSequence = PlayableSequencetype & {
  PlayableSequenceID?: string;
  [k: string]: unknown;
};
export type OtherIDtype = ContentIdentifiertype & {
  [k: string]: unknown;
};
export type EventLocationtypeEarthCoordinate = EventLocationEarthCoordinatetype & {
  [k: string]: unknown;
};
export type EventLocationtypeOtherCoordinates = EventLocationOtherCoordinatetype & {
  [k: string]: unknown;
};
export type InventoryAncillarytype = DigitalAssetAncillaryDatatype & {
  /**
   * @minItems 0
   */
  ContainerReference?: ContainerReferencetype[];
  AncillaryTrackID?: string;
  [k: string]: unknown;
};
export type InventoryMetadatatypeContainerReference = ContainerReferencetype & {
  type?: string;
  [k: string]: unknown;
};
export type BasicMetadatatypeCountryOfOrigin = Regiontype & {
  intepretation?: string;
  [k: string]: unknown;
};
export type ContentRelatedToCharactertype = BasicMetadataCharactertype & {
  /**
   * @minItems 0
   */
  Description?: ContentRelatedToCharactertype1[];
  primary?: boolean;
  fictional?: boolean;
  [k: string]: unknown;
};
export type InventoryTextObjecttypeContainerReference = ContainerReferencetype & {
  type?: string;
  [k: string]: unknown;
};
export type InventoryManifesttypeContainerReference = ContainerReferencetype & {
  type?: string;
  [k: string]: unknown;
};
export type MediaInventorytype = Inventorytype & {
  Compatibility?: Compatibilitytype;
  Source?: ManifestSourcetype;
  type?: string;
  reference?: string;
  ManifestID?: string;
  updateNum?: number;
  workflow?: string;
  updateDeliveryType?: string;
  versionDescription?: string;
  timestamp?: string;
  [k: string]: unknown;
};

export type FileDeleteManifesttype = FileManifesttype & {
  Description?: string;
  Instructions?: string;
  type?: string;
  reference?: string;
  [k: string]: unknown;
};
export interface Presentationtype {
  /**
   * @minItems 1
   */
  TrackMetadata: [PresentationtypeTrackMetadata, ...PresentationtypeTrackMetadata[]];
  /**
   * @minItems 0
   */
  LanguagePair?: PresentationLanguagePairtype[];
  Chapters?: ChapterListtype;
  Markers?: MarkerListtype;
  IMFRef?: PresentationIMFReftype;
  PresentationTimeline?: PresentationTimelinetype;
  PresentationID: string;
  [k: string]: unknown;
}
export interface TrackMetadatatype {
  TrackSelectionNumber: number;
  /**
   * @minItems 0
   */
  VideoTrackReference?: VideoTrackReferencetype[];
  /**
   * @minItems 0
   */
  AudioTrackReference?: AudioTrackReferencetype[];
  /**
   * @minItems 0
   */
  SubtitleTrackReference?: SubtitleTrackReferencetype[];
  /**
   * @minItems 0
   */
  AncillaryTrackReference?: AncillaryTrackReferencetype[];
  /**
   * @minItems 0
   */
  Purpose?: TrackMetadataPurposetype[];
  [k: string]: unknown;
}
export interface VideoTrackReferencetype {
  /**
   * @minItems 1
   */
  VideoTrackID: [string, ...string[]];
  AdaptationSetID?: VideoTrackReferencetype1;
  /**
   * @minItems 0
   */
  TrackProfile?: MediaProfiletype[];
  priority?: number;
  [k: string]: unknown;
}
export interface VideoTrackReferencetype1 {
  Value?: string;
  [k: string]: unknown;
}
export interface MediaProfiletype {
  Namespace: string;
  /**
   * @minItems 1
   */
  Profile: [MediaProfiletype1, ...MediaProfiletype1[]];
  [k: string]: unknown;
}
export interface MediaProfiletype1 {
  Value?: string;
  [k: string]: unknown;
}
export interface AudioTrackReferencetype {
  /**
   * @minItems 1
   */
  AudioTrackID: [string, ...string[]];
  AdaptationSetID?: AudioTrackReferencetype1;
  /**
   * @minItems 0
   */
  TrackProfile?: MediaProfiletype[];
  priority?: number;
  [k: string]: unknown;
}
export interface AudioTrackReferencetype1 {
  Value?: string;
  [k: string]: unknown;
}
export interface SubtitleTrackReferencetype {
  /**
   * @minItems 1
   */
  SubtitleTrackID: [string, ...string[]];
  AdaptationSetID?: SubtitleTrackReferencetype1;
  /**
   * @minItems 0
   */
  TrackProfile?: MediaProfiletype[];
  priority?: number;
  [k: string]: unknown;
}
export interface SubtitleTrackReferencetype1 {
  Value?: string;
  [k: string]: unknown;
}
export interface AncillaryTrackReferencetype {
  /**
   * @minItems 1
   */
  AncillaryTrackID: [string, ...string[]];
  AdaptationSetID?: AncillaryTrackReferencetype1;
  /**
   * @minItems 0
   */
  TrackProfile?: MediaProfiletype[];
  priority?: number;
  [k: string]: unknown;
}
export interface AncillaryTrackReferencetype1 {
  Value?: string;
  [k: string]: unknown;
}
export interface TrackMetadataPurposetype {
  EncodingIntent?: string;
  WorkType?: string;
  /**
   * @minItems 0
   */
  WorkTypeDetail?: string[];
  Description?: string;
  [k: string]: unknown;
}
export interface PresentationLanguagePairtype {
  SystemLanguage: string;
  AudioLanguage: string;
  SubtitleLanguage: string;
  [k: string]: unknown;
}
export interface ChapterListtype {
  /**
   * @minItems 1
   */
  Chapter: [Chaptertype, ...Chaptertype[]];
  [k: string]: unknown;
}
export interface Chaptertype {
  EntryTimecode: Timecodetype;
  /**
   * @minItems 0
   */
  DisplayLabel?: Chaptertype1[];
  /**
   * @minItems 0
   */
  ImageID?: Chaptertype2[];
  index: string | number | number | boolean | null;
  [k: string]: unknown;
}
export interface Timecodetype {
  Value?: string;
  dropframe?: boolean;
  format?: string;
  [k: string]: unknown;
}
export interface Chaptertype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface Chaptertype2 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface MarkerListtype {
  /**
   * @minItems 1
   */
  Marker: [MarkerListtypeMarker, ...MarkerListtypeMarker[]];
  [k: string]: unknown;
}
export interface Markertype {
  Timecode: Timecodetype;
  /**
   * @minItems 0
   */
  DisplayLabel?: Markertype1[];
  Label: Markertype2;
  /**
   * @minItems 0
   */
  ImageID?: Markertype3[];
  [k: string]: unknown;
}
export interface Markertype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface Markertype2 {
  Value?: string;
  namespace?: string;
  [k: string]: unknown;
}
export interface Markertype3 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface PresentationIMFReftype {
  CPLID: string;
  /**
   * @minItems 0
   */
  OPLID?: string[];
  ContainerReference?: ContainerReferencetype;
  [k: string]: unknown;
}
export interface ContainerReferencetype {
  Type?: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  /**
   * @minItems 0
   */
  ContainerLocation?: Locationtype[];
  ParentContainer?: ContainerReferencetype;
  /**
   * @minItems 0
   */
  ContainerIdentifier?: ContentIdentifiertype[];
  /**
   * @minItems 0
   */
  ContainerIntent?: AssetIntenttype[];
  SequenceParsing?: SequenceParsingtype;
  Length?: number;
  /**
   * @minItems 0
   */
  Hash?: Hashtype[];
  [k: string]: unknown;
}
export interface Locationtype {
  Value?: string;
  priority?: number;
  [k: string]: unknown;
}
export interface ContentIdentifiertype {
  Namespace: string;
  Identifier: string;
  Location?: string;
  Scope?: ContentIdentifiertype1;
  [k: string]: unknown;
}
export interface ContentIdentifiertype1 {
  Value?: string;
  subscope?: string;
  [k: string]: unknown;
}
export interface AssetIntenttype {
  Type: string;
  /**
   * @minItems 0
   */
  SubType?: AssetIntenttype1[];
  Description?: AssetIntenttype2;
  /**
   * @minItems 0
   */
  AssetReference?: AssetIntentReferencetype[];
  /**
   * @minItems 0
   */
  AssociatedOrg?: AssociatedOrgtype[];
  WIP?: boolean;
  [k: string]: unknown;
}
export interface AssetIntenttype1 {
  Value?: string;
  ordinal?: number;
  [k: string]: unknown;
}
export interface AssetIntenttype2 {
  Value?: string;
  [k: string]: unknown;
}
export interface AssetIntentReferencetype {
  /**
   * @minItems 0
   */
  ContentID?: string[];
  /**
   * @minItems 0
   */
  OtherIdentifier?: ContentIdentifiertype[];
  /**
   * @minItems 0
   */
  Description?: AssetIntentReferencetype1[];
  [k: string]: unknown;
}
export interface AssetIntentReferencetype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface OrgNametype {
  DisplayName: string;
  SortName?: string;
  /**
   * @minItems 0
   */
  AlternateName?: string[];
  organizationID?: string;
  departmentID?: string;
  idType?: string;
  [k: string]: unknown;
}
export interface SequenceParsingtype {
  PatternSpec?: string;
  StartsWith?: number;
  EndsWith?: number;
  FilenameEmbedding?: SequenceParsingtype1;
  [k: string]: unknown;
}
export interface SequenceParsingtype1 {
  Value?: boolean;
  location?: string;
  preceededBy?: string;
  terminatedBy?: string;
  fixedDigits?: number;
  sequential?: boolean;
  [k: string]: unknown;
}
export interface Hashtype {
  Value?: string;
  method?: string;
  [k: string]: unknown;
}
export interface PresentationTimelinetype {
  PresentationStart?: Timecodetype;
  /**
   * @minItems 0
   */
  AudioTrackStart?: PresentationTimelinetypeAudioTrackStart[];
  /**
   * @minItems 0
   */
  VideoTrackStart?: PresentationTimelinetypeVideoTrackStart[];
  /**
   * @minItems 0
   */
  SubtitleTrackStart?: PresentationTimelinetypeSubtitleTrackStart[];
  framerate?: number;
  multiplier?: string;
  dropframe?: boolean;
  format?: string;
  [k: string]: unknown;
}
export interface FileManifestInfotype {
  PackageID: string;
  PackageDateTime: string;
  Publisher: OrgNametype;
  /**
   * @minItems 0
   */
  AvailsEntryID?: string[];
  TotalFilesInPackage: number;
  /**
   * @minItems 1
   */
  FileInfo: [FileInfotype, ...FileInfotype[]];
  ExceptionFlag?: boolean;
  Comments?: string;
  [k: string]: unknown;
}
export interface FileInfotype {
  /**
   * @minItems 1
   */
  Location: [Locationtype, ...Locationtype[]];
  /**
   * @minItems 0
   */
  Identifier?: ContentIdentifiertype[];
  FileVersion?: number;
  FiileDate?: string;
  Type: "manifest" | "metadata" | "media" | "transaction" | "ancillary";
  Length?: number;
  Hash?: Hashtype;
  MIMEType?: string;
  WrapperFormat?: string;
  ContainerMetadata?: ContainerMetadatatype;
  Delivery?: FileDeliverytype;
  [k: string]: unknown;
}
export interface ContainerMetadatatype {
  Type?: string;
  /**
   * @minItems 1
   */
  Track: [ContainerTrackMetadatatype, ...ContainerTrackMetadatatype[]];
  /**
   * @minItems 0
   */
  Hash?: Hashtype[];
  Size?: number;
  ContainerReference?: string;
  /**
   * @minItems 0
   */
  ContainerIdentifier?: ContentIdentifiertype[];
  /**
   * @minItems 0
   */
  ContainerIntent?: AssetIntenttype[];
  ContainerSpecificMetadata?: ContainerSpecifictype;
  /**
   * @minItems 0
   */
  Any?: {
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface ContainerTrackMetadatatype {
  Audio: DigitalAssetAudioDatatype;
  Video: DigitalAssetVideoDatatype;
  Subtitle: DigitalAssetSubtitleDatatype;
  Image: DigitalAssetImageDatatype;
  Interactive: DigitalAssetInteractiveDatatype;
  Container: ContainerMetadatatype;
  ExternalTrackReference: DigitalAssetExternalTrackReferencetype;
  InternalTrackReference: string;
  [k: string]: unknown;
}
export interface DigitalAssetAudioDatatype {
  /**
   * @minItems 0
   */
  Description?: DigitalAssetAudioDatatype1[];
  Type?: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  Encoding?: DigitalAssetAudioEncodingtype;
  /**
   * @minItems 1
   */
  Language: [DigitalAssetAudioLanguagetype, ...DigitalAssetAudioLanguagetype[]];
  /**
   * @minItems 0
   */
  People?: BasicMetadataPeopletype[];
  Channels?: string;
  MCALabelSubdescriptor?: DigitalAssetAudioMCALabeltype;
  /**
   * @minItems 0
   */
  Compliance?: Compliancetype[];
  /**
   * @minItems 0
   */
  AssetIntent?: AssetIntenttype[];
  TrackReference?: string;
  /**
   * @minItems 0
   */
  TrackIdentifier?: ContentIdentifiertype[];
  Private?: PrivateDatatype;
  [k: string]: unknown;
}
export interface DigitalAssetAudioDatatype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface DigitalAssetAudioEncodingtype {
  Codec: string;
  /**
   * @minItems 0
   */
  CodecType?: string[];
  BitrateMax?: number;
  BitrateAverage?: number;
  VBR?: string;
  SampleRate?: number;
  SampleBitDepth?: number;
  ChannelMapping?: DigitalAssetAudioEncodingtype1;
  /**
   * @minItems 0
   */
  Watermark?: DigitalAssetWatermarktype[];
  ActualLength?: string;
  Ambisonics?: DigitalAssetAudioAmbisonicstype;
  Loudness?: DigitalAssetAudioLoudnesstype;
  [k: string]: unknown;
}
export interface DigitalAssetAudioEncodingtype1 {
  Value?: string;
  isSingleTrack?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetWatermarktype {
  Vendor: string;
  ProductAndVersionID: string;
  Data?: string;
  guaranteedAbsent?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetAudioAmbisonicstype {
  Type?: string;
  Order: number;
  VeriticalOrder?: number;
  Normalization: string;
  [k: string]: unknown;
}
export interface DigitalAssetAudioLoudnesstype {
  Level?: number;
  Deviation?: number;
  LeqM?: number;
  /**
   * @minItems 0
   */
  Compliance?: string[];
  [k: string]: unknown;
}
export interface DigitalAssetAudioLanguagetype {
  Value?: string;
  dubbed?: boolean;
  forced?: boolean;
  disposition?: string;
  [k: string]: unknown;
}
export interface BasicMetadataPeopletype {
  /**
   * @minItems 1
   */
  Job: [BasicMetadataJobtype, ...BasicMetadataJobtype[]];
  Name: PersonNametype;
  /**
   * @minItems 0
   */
  Identifier?: PersonIdentifiertype[];
  Gender?: Gendertype;
  Pronouns?: Pronounstype;
  Salutations?: Salutationstype;
  /**
   * @minItems 0
   */
  ImageReference?: BasicMetadataPeopletype1[];
  /**
   * @minItems 0
   */
  Biography?: BasicMetadataPeopletype2[];
  [k: string]: unknown;
}
export interface BasicMetadataJobtype {
  JobFunction: BasicMetadataJobtype1;
  /**
   * @minItems 0
   */
  JobDisplay?: BasicMetadataJobtype2[];
  /**
   * @minItems 0
   */
  BillingBlockOrder?: BasicMetadataJobtype3[];
  /**
   * @minItems 0
   */
  Character?: string[];
  /**
   * @minItems 0
   */
  CharacterInfo?: BasicMetadataCharactertype[];
  Guest?: boolean;
  [k: string]: unknown;
}
export interface BasicMetadataJobtype1 {
  Value?: string;
  scheme?: string;
  [k: string]: unknown;
}
export interface BasicMetadataJobtype2 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface BasicMetadataJobtype3 {
  Value?: number;
  topBilled?: boolean;
  region?: string[];
  [k: string]: unknown;
}
export interface BasicMetadataCharactertype {
  /**
   * @minItems 1
   */
  CharacterName: [BasicMetadataCharactertype1, ...BasicMetadataCharactertype1[]];
  /**
   * @minItems 0
   */
  CharacterID?: PersonIdentifiertype[];
  Nonfictional?: BasicMetadataCharactertype2;
  /**
   * @minItems 0
   */
  Gender?: Gendertype[];
  Pronouns?: Pronounstype;
  Salutations?: Salutationstype;
  /**
   * @minItems 0
   */
  GroupingEntity?: GroupingEntitytype[];
  /**
   * @minItems 0
   */
  ImageReference?: BasicMetadataCharactertype3[];
  /**
   * @minItems 0
   */
  CharacterDescription?: BasicMetadataCharactertype4[];
  sequence?: number;
  [k: string]: unknown;
}
export interface BasicMetadataCharactertype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface PersonIdentifiertype {
  Identifier: string;
  Namespace: string;
  ReferenceLocation?: string;
  Scope?: PersonIdentifiertype1;
  [k: string]: unknown;
}
export interface PersonIdentifiertype1 {
  Value?: string;
  subscope?: string;
  [k: string]: unknown;
}
export interface BasicMetadataCharactertype2 {
  Value?: boolean;
  appearance?: string;
  [k: string]: unknown;
}
export interface Gendertype {
  Value?: string;
  transgender?: boolean;
  specificGender?: string;
  [k: string]: unknown;
}
export interface Pronounstype {
  Subjective?: string;
  Objective?: string;
  Adjective?: string;
  Possessive?: string;
  Reflexive?: string;
  noProunouns?: boolean;
  [k: string]: unknown;
}
export interface Salutationstype {
  /**
   * @minItems 0
   */
  Title?: Salutationstype1[];
  noTitle?: boolean;
  [k: string]: unknown;
}
export interface Salutationstype1 {
  Value?: string;
  _default?: boolean;
  [k: string]: unknown;
}
export interface GroupingEntitytype {
  Type: string;
  GroupIdentity: string;
  /**
   * @minItems 1
   */
  DisplayName: [GroupingEntitytype1, ...GroupingEntitytype1[]];
  Region?: Regiontype;
  /**
   * @minItems 0
   */
  AltGroupIdentifier?: ContentIdentifiertype[];
  [k: string]: unknown;
}
export interface GroupingEntitytype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface Regiontype {
  country: string;
  countryRegion: string;
  [k: string]: unknown;
}
export interface BasicMetadataCharactertype3 {
  Value?: string;
  resolution?: string;
  purpose?: string;
  [k: string]: unknown;
}
export interface BasicMetadataCharactertype4 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface PersonNametype {
  /**
   * @minItems 1
   */
  DisplayName: [StringAndLanguagetype, ...StringAndLanguagetype[]];
  /**
   * @minItems 0
   */
  SortName?: StringAndLanguagetype[];
  FirstGivenName?: string;
  SecondGivenName?: string;
  FamilyName?: string;
  Suffix?: string;
  Moniker?: string;
  [k: string]: unknown;
}
export interface StringAndLanguagetype {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface BasicMetadataPeopletype1 {
  Value?: string;
  resolution?: string;
  purpose?: string;
  [k: string]: unknown;
}
export interface BasicMetadataPeopletype2 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface DigitalAssetAudioMCALabeltype {
  ContentKind?: string;
  ElementKind?: string;
  Content?: string;
  UseClass?: string;
  ContentSubtype?: string;
  ContentDifferentiator?: string;
  [k: string]: unknown;
}
export interface Compliancetype {
  Category?: string;
  Standard?: string;
  /**
   * @minItems 0
   */
  StandardDetail?: string[];
  Disposition: string;
  CompetentAuthority?: AssociatedOrgtype;
  Certificate?: Compliancetype1;
  TestingOrganization?: AssociatedOrgtype;
  TestingMethod?: string;
  TestingDate?: string;
  /**
   * @minItems 0
   */
  ErrorDescription?: QCErrorDescriptiontype[];
  Comments?: string;
  [k: string]: unknown;
}
export interface Compliancetype1 {
  Value?: number[];
  MIME?: string;
  [k: string]: unknown;
}
export interface QCErrorDescriptiontype {
  ErrorReference?: string;
  ErrorCategory: string;
  ErrorTerm: string;
  CategorySpecificInfo?: QCCategoryErrortype;
  Comments?: string;
  FullOrPartialQC?: string;
  QCReportLocation?: string;
  Severity?: QCErrorDescriptiontype1;
  [k: string]: unknown;
}
export interface QCCategoryErrortype {
  /**
   * @minItems 1
   */
  AudioOrVideoOrTimedText: [
    (
      | QCCategoryErrortypeAudio
      | QCCategoryErrortypeVideo
      | QCCategoryErrortypeTimedText
      | QCCategoryErrortypeArtwork
      | QCErrorPackagetype
      | QCCategoryErrortypeMetadata
      | QCXMLErrortype
      | QCErrorExceltype
    ),
    ...(
      | QCCategoryErrortypeAudio
      | QCCategoryErrortypeVideo
      | QCCategoryErrortypeTimedText
      | QCCategoryErrortypeArtwork
      | QCErrorPackagetype
      | QCCategoryErrortypeMetadata
      | QCXMLErrortype
      | QCErrorExceltype
    )[]
  ];
  [k: string]: unknown;
}
export interface QCErrorAudiotype {
  TimeRange?: QCTimeRangetype;
  TimeOffset?: string;
  [k: string]: unknown;
}
export interface QCTimeRangetype {
  StartTimecode: Timecodetype2;
  EndTimecode?: Timecodetype2;
  [k: string]: unknown;
}
export interface Timecodetype2 {
  Value?: string;
  dropframe?: boolean;
  format?: string;
  [k: string]: unknown;
}
export interface QCErrorVideotype {
  TimeRange?: QCTimeRangetype;
  Area?: QCAreatype;
  [k: string]: unknown;
}
export interface QCAreatype {
  XOffset: number;
  YOffset: number;
  Width: number;
  Height: number;
  [k: string]: unknown;
}
export interface QCErrorTimedTexttype {
  TimeRange?: QCTimeRangetype;
  TimeOffset?: string;
  Text?: string;
  [k: string]: unknown;
}
export interface QCErrorArtworktype {
  Area?: QCAreatype;
  Text?: string;
  [k: string]: unknown;
}
export interface QCErrorPackagetype {
  /**
   * @minItems 1
   */
  ObjectInError: [QCErrorPackagetype1, ...QCErrorPackagetype1[]];
  [k: string]: unknown;
}
export interface QCErrorPackagetype1 {
  Value?: string;
  disposition?: string;
  [k: string]: unknown;
}
export interface QCErrorMetadatatype {
  XMLError: QCXMLErrortype;
  [k: string]: unknown;
}
export interface QCXMLErrortype {
  XPath?: string;
  LineNumber?: number;
  ValidatorLevel?: string;
  ValidatorTag?: string;
  ValidatorSummary?: string;
  ValidatorFile?: string;
  [k: string]: unknown;
}
export interface QCErrorExceltype {
  Row: number;
  Column: string;
  Cell: QCErrorExceltype1;
  ValidatorLevel?: string;
  ValidatorTag?: string;
  ValidatorSummary?: string;
  [k: string]: unknown;
}
export interface QCErrorExceltype1 {
  Value?: string;
  endCell?: string;
  [k: string]: unknown;
}
export interface QCErrorDescriptiontype1 {
  Value?: string;
  resolution?: string;
  originalSeverity?: string;
  [k: string]: unknown;
}
export interface PrivateDatatype {
  /**
   * @minItems 1
   */
  Any: [
    {
      [k: string]: unknown;
    },
    ...{
      [k: string]: unknown;
    }[]
  ];
  [k: string]: unknown;
}
export interface DigitalAssetVideoDatatype {
  /**
   * @minItems 0
   */
  Description?: DigitalAssetVideoDatatype1[];
  Type?: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  Encoding?: DigitalAssetVideoEncodingtype;
  Picture?: DigitalAssetVideoPicturetype;
  ColorType?: ColorTypetype;
  PictureFormat?: string;
  /**
   * @minItems 0
   */
  CaptureMethod?: string[];
  /**
   * @minItems 0
   */
  Language?: DigitalAssetVideoDatatype2[];
  /**
   * @minItems 0
   */
  SubtitleLanguage?: DigitalAssetVideoSubtitleLanguagetype[];
  SignedLanguage?: DigitalAssetVideoDatatype3;
  /**
   * @minItems 0
   */
  CardsetList?: DigitalAssetCardsetListtype[];
  /**
   * @minItems 0
   */
  Compliance?: Compliancetype[];
  /**
   * @minItems 0
   */
  AssetIntent?: AssetIntenttype[];
  TrackReference?: string;
  /**
   * @minItems 0
   */
  TrackIdentifier?: ContentIdentifiertype[];
  Private?: PrivateDatatype;
  [k: string]: unknown;
}
export interface DigitalAssetVideoDatatype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface DigitalAssetVideoEncodingtype {
  Codec: string;
  /**
   * @minItems 0
   */
  CodecType?: string[];
  MPEGProfile?: string;
  MPEGLevel?: string;
  CodecProfile?: string;
  BitrateMax?: number;
  BitRateAverage?: number;
  VBR?: string;
  /**
   * @minItems 0
   */
  Watermark?: DigitalAssetWatermarktype[];
  ActualLength?: string;
  [k: string]: unknown;
}
export interface DigitalAssetVideoPicturetype {
  AspectRatio?: DigitalAssetVideoPicturetype1;
  PixelAspect?: StringVideoPicPixelAspect;
  WidthPixels?: number;
  HeightPixels?: number;
  ActiveWidthPixels?: DigitalAssetVideoPicturetype2;
  ActiveHeightPixels?: DigitalAssetVideoPicturetype3;
  FrameRate?: DigitalAssetVideoPictureFrameRatetype;
  Progressive?: DigitalAssetVideoPictureProgressivetype;
  ColorSubsampling?: string;
  BitDepth?: DigitalAssetVideoPicturetype4;
  Colorimetry?: string;
  Type3D?: string;
  MasteredColorVolume?: DigitalAssetColorVolumetype;
  ColorEncoding?: DigitalAssetColorEncodingtype;
  /**
   * @minItems 0
   */
  ColorTransformMetadata?: DigitalAssetColorTransformMetadatatype[];
  LightLevel?: DigitalAssetVideoPictureLightLeveltype;
  HDRPlaybackInfo?: DigitalAssetVideoPictureHDRPlaybackInfotype;
  ThreeSixty?: DigitalAssetVideoPicture360Type;
  OriginalPicture?: DigitalAssetVideoPictureOriginaltype;
  /**
   * @minItems 0
   */
  Any?: {
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface DigitalAssetVideoPicturetype1 {
  Value?: string;
  original?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetVideoPicturetype2 {
  Value?: number;
  xOffset?: number;
  [k: string]: unknown;
}
export interface DigitalAssetVideoPicturetype3 {
  Value?: number;
  yOffset?: number;
  [k: string]: unknown;
}
export interface DigitalAssetVideoPictureFrameRatetype {
  Value?: number;
  multiplier?: "1000/1001";
  timecode?: string;
  [k: string]: unknown;
}
export interface DigitalAssetVideoPictureProgressivetype {
  Value?: boolean;
  scanOrder?: StringVideoPicProgressivescanOrder;
  [k: string]: unknown;
}
export interface DigitalAssetVideoPicturetype4 {
  Value?: number;
  alphaDepth?: number;
  [k: string]: unknown;
}
export interface DigitalAssetColorVolumetype {
  PrimaryRChromaticity: DigitalAssetChromaticitytype;
  PrimaryGChromaticity: DigitalAssetChromaticitytype;
  PrimaryBChromaticity: DigitalAssetChromaticitytype;
  WhitePointChromaticity: DigitalAssetChromaticitytype;
  LuminanceMin: number;
  LuminanceMax: number;
  [k: string]: unknown;
}
export interface DigitalAssetChromaticitytype {
  ChromaticityCIEx: number;
  ChromaticityCIEy: number;
  [k: string]: unknown;
}
export interface DigitalAssetColorEncodingtype {
  Primaries: string;
  TransferFunction: string;
  ColorDifferencing: string;
  [k: string]: unknown;
}
export interface DigitalAssetColorTransformMetadatatype {
  ColorVolumeTransform: string;
  ApplicationIdentifier?: DigitalAssetColorTransformMetadatatype1;
  TargetSystemDisplay?: DigitalAssetColorVolumetype;
  DoNotTranscodeBase?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetColorTransformMetadatatype1 {
  Value?: number;
  applicationVersion?: number;
  [k: string]: unknown;
}
export interface DigitalAssetVideoPictureLightLeveltype {
  /**
   * @minItems 0
   */
  ContentMax?: DigitalAssetVideoPictureLightLeveltype1[];
  /**
   * @minItems 0
   */
  FrameAverageMax?: DigitalAssetVideoPictureLightLeveltype2[];
  [k: string]: unknown;
}
export interface DigitalAssetVideoPictureLightLeveltype1 {
  Value?: number;
  interpretation?: string;
  [k: string]: unknown;
}
export interface DigitalAssetVideoPictureLightLeveltype2 {
  Value?: number;
  interpretation?: string;
  [k: string]: unknown;
}
export interface DigitalAssetVideoPictureHDRPlaybackInfotype {
  SDRDownconversion?: string;
  /**
   * @minItems 0
   */
  Any?: {
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface DigitalAssetVideoPicture360Type {
  Projection: string;
  Rendering?: string;
  InitialView?: DigitalAssetVideoPicture360Initialtype;
  [k: string]: unknown;
}
export interface DigitalAssetVideoPicture360Initialtype {
  HeadingDegrees: number;
  PitchDegrees: number;
  RollDegress: number;
  [k: string]: unknown;
}
export interface DigitalAssetVideoPictureOriginaltype {
  FrameRate?: DigitalAssetVideoPictureFrameRatetype;
  Progressive?: DigitalAssetVideoPictureProgressivetype;
  [k: string]: unknown;
}
export interface DigitalAssetVideoDatatype2 {
  Value?: string;
  disposition?: string;
  [k: string]: unknown;
}
export interface DigitalAssetVideoSubtitleLanguagetype {
  Value?: string;
  closed?: boolean;
  type?: string;
  disposition?: string;
  [k: string]: unknown;
}
export interface DigitalAssetVideoDatatype3 {
  Value?: string;
  disposition?: string;
  [k: string]: unknown;
}
export interface DigitalAssetCardsetListtype {
  /**
   * @minItems 0
   */
  Type?: string[];
  /**
   * @minItems 0
   */
  Region?: string[];
  /**
   * @minItems 1
   */
  Cardset: [DigitalAssetCardsettype, ...DigitalAssetCardsettype[]];
  [k: string]: unknown;
}
export interface DigitalAssetCardsettype {
  /**
   * @minItems 1
   */
  Type: [string, ...string[]];
  Description?: string;
  Sequence?: number;
  /**
   * @minItems 0
   */
  Language?: string[];
  [k: string]: unknown;
}
export interface DigitalAssetSubtitleDatatype {
  Format?: DigitalAssetSubtitleFormattype;
  /**
   * @minItems 0
   */
  Description?: DigitalAssetSubtitleDatatype1[];
  /**
   * @minItems 1
   */
  Type: [string, ...string[]];
  /**
   * @minItems 0
   */
  SubType?: string[];
  FormatType?: string;
  /**
   * @minItems 1
   */
  Language: [DigitalAssetSubtitleDatatype2, ...DigitalAssetSubtitleDatatype2[]];
  Encoding?:
    | string
    | number
    | number
    | boolean
    | null
    | {
        [k: string]: unknown;
      }
    | unknown[];
  Properties?: DigitalAssetSubtitlePropertiestype;
  PictureDetails?: DigitalAssetVideoPicturetype;
  DynamicRangeProfile?: DigitalAssetSubtitleDatatype3;
  ColorGamutProfile?: string;
  Creation?: DigitalAssetSubtitleCreationtype;
  AdditionalOffset?: Timecodetype2;
  DropFrame?: boolean;
  /**
   * @minItems 0
   */
  CardsetList?: DigitalAssetCardsetListtype[];
  /**
   * @minItems 0
   */
  Compliance?: Compliancetype[];
  /**
   * @minItems 0
   */
  AssetIntent?: AssetIntenttype[];
  TrackReference?: string;
  /**
   * @minItems 0
   */
  TrackIdentifier?: ContentIdentifiertype[];
  Private?: PrivateDatatype;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitleFormattype {
  Value?: string;
  SDImage?: boolean;
  HDImage?: boolean;
  UHDImage?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitleDatatype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitleDatatype2 {
  Value?: string;
  disposition?: string;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitlePropertiestype {
  MaxCPS?: DigitalAssetSubtitlePropertiestype1;
  MaxLinesPerEvent?: DigitalAssetSubtitlePropertiestype2;
  FormattingStripped?: boolean;
  /**
   * @minItems 0
   */
  ContainsAnnotation?: DigitalAssetSubtitlePropertiestype3[];
  /**
   * @minItems 0
   */
  WritingFeatures?: Termstype[];
  [k: string]: unknown;
}
export interface DigitalAssetSubtitlePropertiestype1 {
  Value?: number;
  strict?: boolean;
  algorithm?: string;
  spacesCounted?: boolean;
  punctuationCounted?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitlePropertiestype2 {
  Value?: number;
  strict?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitlePropertiestype3 {
  Value?: boolean;
  type?: string;
  [k: string]: unknown;
}
export interface Termstype {
  Money: Moneytype;
  Event: string;
  Text: string;
  Boolean: boolean;
  Duration: string;
  URI: string;
  Language: string;
  ID: string;
  AltIdentifier: ContentIdentifiertype;
  YearDateTime: string;
  Time: string;
  Region: Regiontype;
  Timecode: Timecodetype2;
  Any: {
    [k: string]: unknown;
  };
  termName: string;
  [k: string]: unknown;
}
export interface Moneytype {
  Value?: number;
  currency?: string;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitleDatatype3 {
  Value?: string;
  LuminanceMin?: number;
  LuminanceMax?: number;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitleCreationtype {
  AutoTTS?: DigitalAssetSubtitleCreationtype1;
  AutoSegmentation?: DigitalAssetSubtitleCreationtype2;
  AutoTranslation?: DigitalAssetSubtitleCreationtype3;
  OCR?: DigitalAssetSubtitleCreationtype4;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitleCreationtype1 {
  Value?: boolean;
  full?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitleCreationtype2 {
  Value?: boolean;
  full?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitleCreationtype3 {
  Value?: boolean;
  full?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetSubtitleCreationtype4 {
  Value?: boolean;
  full?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetImageDatatype {
  /**
   * @minItems 0
   */
  Description?: DigitalAssetImageDatatype1[];
  /**
   * @minItems 0
   */
  Type?: string[];
  /**
   * @minItems 0
   */
  SubType?: string[];
  /**
   * @minItems 0
   */
  Purpose?: string[];
  Width: number;
  Height: number;
  Encoding: string;
  PictureDetails?: DigitalAssetVideoPicturetype;
  DynamicRangeProfile?: DigitalAssetImageDatatype2;
  ColorGamutProfile?: string;
  /**
   * @minItems 0
   */
  Language?: DigitalAssetImageDatatype3[];
  /**
   * @minItems 0
   */
  CardsetList?: DigitalAssetCardsetListtype[];
  /**
   * @minItems 0
   */
  Compliance?: Compliancetype[];
  /**
   * @minItems 0
   */
  AssetIntent?: AssetIntenttype[];
  TrackReference?: string;
  /**
   * @minItems 0
   */
  TrackIdentifier?: ContentIdentifiertype[];
  Private?: PrivateDatatype;
  [k: string]: unknown;
}
export interface DigitalAssetImageDatatype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface DigitalAssetImageDatatype2 {
  Value?: string;
  LuminanceMin?: number;
  LuminanceMax?: number;
  [k: string]: unknown;
}
export interface DigitalAssetImageDatatype3 {
  Value?: string;
  disposition?: string;
  [k: string]: unknown;
}
export interface DigitalAssetInteractiveDatatype {
  Type: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  FormatType?: string;
  Language?: string;
  /**
   * @minItems 1
   */
  Encoding: [DigitalAssetInteractiveEncodingtype, ...DigitalAssetInteractiveEncodingtype[]];
  /**
   * @minItems 0
   */
  Compliance?: Compliancetype[];
  /**
   * @minItems 0
   */
  AssetIntent?: AssetIntenttype[];
  TrackReference?: string;
  /**
   * @minItems 0
   */
  TrackIdentifier?: ContentIdentifiertype[];
  Private?: PrivateDatatype;
  [k: string]: unknown;
}
export interface DigitalAssetInteractiveEncodingtype {
  RuntimeEnvironment: string;
  /**
   * @minItems 0
   */
  EnvironmentAttribute?: DigitalAssetInteractiveEncodingtype1[];
  FirstVersion?: string;
  LastVersion?: string;
  /**
   * @minItems 0
   */
  Any?: {
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface DigitalAssetInteractiveEncodingtype1 {
  Value?: string;
  recommended?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetExternalTrackReferencetype {
  Value?: string;
  namespace?: string;
  location?: string;
  trackReference?: string;
  [k: string]: unknown;
}
export interface ContainerSpecifictype {
  /**
   * @minItems 0
   */
  Any?: {
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface FileDeliverytype {
  UpdateNum?:
    | string
    | number
    | number
    | boolean
    | null
    | {
        [k: string]: unknown;
      }
    | unknown[];
  DeliveryMethod: string;
  TransferLocation?: string;
  Organization?: OrgNametype;
  Contact?: ContactInfotype;
  EstDeliveryDate?: string;
  OtherInstructions?: string;
  [k: string]: unknown;
}
export interface ContactInfotype {
  Name: string;
  PrimaryEmail: string;
  /**
   * @minItems 0
   */
  AlternateEmail?: string[];
  /**
   * @minItems 0
   */
  Address?: string[];
  /**
   * @minItems 0
   */
  Phone?: ContactInfotype1[];
  [k: string]: unknown;
}
export interface ContactInfotype1 {
  Value?: string;
  type?: string;
  [k: string]: unknown;
}
export interface MediaManifesttype {
  Compatibility: Compatibilitytype;
  Source?: ManifestSourcetype;
  Inventory: Inventorytype;
  Presentations?: PresentationListtype;
  PlayableSequences?: PlayableSequenceListtype;
  PictureGroups?: PictureGroupListtype;
  AppGroups?: AppGroupListtype;
  TextGroups?: TextGroupListtype;
  Experiences: ExperienceListtype;
  TimedEventSequences?: TimedEventSequenceListtype;
  ALIDExperienceMaps?: ALIDExperienceMapListtype;
  ManifestID?: string;
  ExtraVersionReference?: string;
  updateNum?: number;
  workflow?: string;
  updateDeliveryType?: string;
  versionDescription?: string;
  timestamp?: string;
  [k: string]: unknown;
}
export interface Compatibilitytype {
  SpecVersion: string;
  /**
   * @minItems 0
   */
  System?: string[];
  Profile: Compatibilitytype1;
  /**
   * @minItems 0
   */
  ValidatorParameter?: Termstype[];
  [k: string]: unknown;
}
export interface Compatibilitytype1 {
  Value?: string;
  subProfile?: string;
  [k: string]: unknown;
}
export interface ManifestSourcetype {
  ServiceProvider?: OrgNametype;
  /**
   * @minItems 0
   */
  Licensor?: ManifestSourceLicensortype[];
  DeliveryContact?: ContactInfotype;
  [k: string]: unknown;
}
export interface Inventorytype {
  /**
   * @minItems 0
   */
  Audio?: InventoryAudiotype[];
  /**
   * @minItems 0
   */
  Video?: InventoryVideotype[];
  /**
   * @minItems 0
   */
  Subtitle?: InventorySubtitletype[];
  /**
   * @minItems 0
   */
  Image?: InventoryImagetype[];
  /**
   * @minItems 0
   */
  Interactive?: InventoryInteractivetype[];
  /**
   * @minItems 0
   */
  Ancillary?: InventoryAncillarytype[];
  /**
   * @minItems 0
   */
  Metadata?: InventoryMetadatatype[];
  /**
   * @minItems 0
   */
  TextObject?: InventoryTextObjecttype[];
  /**
   * @minItems 0
   */
  ExternalManifest?: InventoryManifesttype[];
  [k: string]: unknown;
}
export interface InventoryMediaManifesttype {
  Compatibility?: Compatibilitytype;
  Inventory?: Inventorytype;
  Presentations?: PresentationListtype;
  PlayableSequences?: PlayableSequenceListtype;
  PictureGroups?: PictureGroupListtype;
  AppGroups?: AppGroupListtype;
  TextGroups?: TextGroupListtype;
  Experiences: ExperienceListtype;
  TimedEventSequences?: TimedEventSequenceListtype;
  ALIDExperienceMaps?: ALIDExperienceMapListtype;
  ManifestID?: string;
  updateNum?: number;
  ExtraVersionReference?: string;
  updateDeliveryType?: string;
  profile?: string;
  [k: string]: unknown;
}
export interface PresentationListtype {
  /**
   * @minItems 1
   */
  Presentation: [Presentationtype, ...Presentationtype[]];
  [k: string]: unknown;
}
export interface PlayableSequenceListtype {
  /**
   * @minItems 1
   */
  PlayableSequence: [PlayableSequenceListtypePlayableSequence, ...PlayableSequenceListtypePlayableSequence[]];
  [k: string]: unknown;
}
export interface PlayableSequencetype {
  /**
   * @minItems 1
   */
  Clip: [AudiovisualClipReftype, ...AudiovisualClipReftype[]];
  /**
   * @minItems 0
   */
  ImageClip?: ImageClipReftype[];
  /**
   * @minItems 0
   */
  ReferenceID?: ContentIdentifiertype[];
  SequenceTimeline?: PresentationTimelinetype;
  [k: string]: unknown;
}
export interface AudiovisualClipReftype {
  PresentationID: string;
  EntryPointTimecode?: Timecodetype;
  ExitPointTimecode?: Timecodetype;
  /**
   * @minItems 0
   */
  Region?: Regiontype[];
  /**
   * @minItems 0
   */
  Purpose?: TrackMetadataPurposetype[];
  CardsetSeq?: number;
  Branching?: PlayableBranchtype;
  sequence?: number;
  seamless?: boolean;
  audioLanguage?: string;
  [k: string]: unknown;
}
export interface PlayableBranchtype {
  /**
   * @minItems 1
   */
  BranchChoice: [PlayableBranchChoicetype, ...PlayableBranchChoicetype[]];
  branchStateID?: string;
  [k: string]: unknown;
}
export interface PlayableBranchChoicetype {
  /**
   * @minItems 0
   */
  Applicability?: string[];
  /**
   * @minItems 1
   */
  Label: [PlayableBranchChoicetype1, ...PlayableBranchChoicetype1[]];
  /**
   * @minItems 0
   */
  DescriptionID?: string[];
  NextSequenceID: PlayableBranchChoicetype2;
  branchChoiceID?: string;
  [k: string]: unknown;
}
export interface PlayableBranchChoicetype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface PlayableBranchChoicetype2 {
  Value?: string;
  sequence?: number;
  [k: string]: unknown;
}
export interface ImageClipReftype {
  ImageID: string;
  Duration: string;
  /**
   * @minItems 0
   */
  Region?: Regiontype[];
  /**
   * @minItems 0
   */
  Purpose?: TrackMetadataPurposetype[];
  CardsetSeq?: number;
  Branching?: PlayableBranchtype;
  sequence?: number;
  seamless?: boolean;
  audioLanguage?: string;
  [k: string]: unknown;
}
export interface PictureGroupListtype {
  /**
   * @minItems 1
   */
  PictureGroup: [PictureGrouptype, ...PictureGrouptype[]];
  [k: string]: unknown;
}
export interface PictureGrouptype {
  /**
   * @minItems 1
   */
  Picture: [Picturetype, ...Picturetype[]];
  Type?: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  /**
   * @minItems 0
   */
  StyleRef?: string[];
  PictureGroupID?: string;
  [k: string]: unknown;
}
export interface Picturetype {
  PictureID: string;
  /**
   * @minItems 1
   */
  ImageID: [Picturetype1, ...Picturetype1[]];
  /**
   * @minItems 0
   */
  ThumbnailImageID?: Picturetype2[];
  /**
   * @minItems 0
   */
  LanguageInImage?: string[];
  /**
   * @minItems 0
   */
  AlternateText?: Picturetype3[];
  /**
   * @minItems 0
   */
  Caption?: Picturetype4[];
  Sequence?: number;
  /**
   * @minItems 0
   */
  Purpose?: string[];
  [k: string]: unknown;
}
export interface Picturetype1 {
  Value?: string;
  resolution?: string;
  [k: string]: unknown;
}
export interface Picturetype2 {
  Value?: string;
  resolution?: string;
  [k: string]: unknown;
}
export interface Picturetype3 {
  Value?: string;
  language?: string | number | number | boolean | null;
  [k: string]: unknown;
}
export interface Picturetype4 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface AppGroupListtype {
  /**
   * @minItems 1
   */
  AppGroup: [AppGrouptype, ...AppGrouptype[]];
  [k: string]: unknown;
}
export interface AppGrouptype {
  /**
   * @minItems 1
   */
  InteractiveTrackReference: [InteractiveTrackReferencetype, ...InteractiveTrackReferencetype[]];
  AppGroupID: string;
  [k: string]: unknown;
}
export interface InteractiveTrackReferencetype {
  InteractiveTrackID: string;
  /**
   * @minItems 1
   */
  Compatibility: [DigitalAssetInteractiveEncodingtype, ...DigitalAssetInteractiveEncodingtype[]];
  priority?: number;
  [k: string]: unknown;
}
export interface TextGroupListtype {
  /**
   * @minItems 1
   */
  TextGroup: [TextGrouptype, ...TextGrouptype[]];
  [k: string]: unknown;
}
export interface TextGrouptype {
  /**
   * @minItems 1
   */
  TextObjectID: [string, ...string[]];
  TextGroupID: string;
  language?: string;
  [k: string]: unknown;
}
export interface ExperienceListtype {
  /**
   * @minItems 1
   */
  Experience: [Experiencetype, ...Experiencetype[]];
  [k: string]: unknown;
}
export interface Experiencetype {
  Type?: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  /**
   * @minItems 1
   */
  Language: [string, ...string[]];
  /**
   * @minItems 1
   */
  ExcludedLanguage: [string, ...string[]];
  /**
   * @minItems 1
   */
  Region: [Regiontype, ...Regiontype[]];
  /**
   * @minItems 1
   */
  ExcludedRegion: [Regiontype, ...Regiontype[]];
  ContentID?: string;
  Audiovisual?: Audiovisualtype;
  App?: ExperienceApptype;
  Gallery?: Gallerytype;
  /**
   * @minItems 0
   */
  PictureGroupID?: string[];
  /**
   * @minItems 0
   */
  TextGroupID?: string[];
  /**
   * @minItems 0
   */
  TimedSequenceID?: string[];
  /**
   * @minItems 0
   */
  ExperienceChild?: ExperienceChildtype[];
  updateNum?: number;
  ExperienceID?: string;
  version: string;
  [k: string]: unknown;
}
export interface Audiovisualtype {
  Type: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  PresentationID: string;
  PlayableSequenceID: string;
  PlayableSequence: PlayableSequencetype;
  ContentID: string;
  [k: string]: unknown;
}
export interface ExperienceApptype {
  Type: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  AppGroupID?: string;
  /**
   * @minItems 0
   */
  AppName?: ExperienceApptype1[];
  /**
   * @minItems 0
   */
  Rating?: ContentRatingtype[];
  ContentID?: string;
  AppID?: string;
  [k: string]: unknown;
}
export interface ExperienceApptype1 {
  Value?: string;
  language?: boolean;
  [k: string]: unknown;
}
export interface ContentRatingtype {
  NotRated: ContentRatingtype1;
  /**
   * @minItems 1
   */
  Rating: [ContentRatingDetailtype, ...ContentRatingDetailtype[]];
  AdultContent?: boolean;
  [k: string]: unknown;
}
export interface ContentRatingtype1 {
  Value?: boolean;
  condition?: string;
  [k: string]: unknown;
}
export interface ContentRatingDetailtype {
  Region: Regiontype;
  System: string;
  Value: string;
  /**
   * @minItems 0
   */
  Reason?: ContentRatingDetailtype1[];
  /**
   * @minItems 0
   */
  LinkToLogo?: ContentRatingDetailtype2[];
  /**
   * @minItems 0
   */
  Description?: ContentRatingDetailtype3[];
  [k: string]: unknown;
}
export interface ContentRatingDetailtype1 {
  Value?: string;
  value?: string;
  [k: string]: unknown;
}
export interface ContentRatingDetailtype2 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface ContentRatingDetailtype3 {
  Value?: string;
  language?: string;
  authoritative?: boolean;
  origin?: string;
  [k: string]: unknown;
}
export interface Gallerytype {
  Type:
    | string
    | number
    | number
    | boolean
    | null
    | {
        [k: string]: unknown;
      }
    | unknown[];
  /**
   * @minItems 0
   */
  SubType?: string[];
  PictureGroupID?: string;
  /**
   * @minItems 0
   */
  GalleryName?: Gallerytype1[];
  ContentID?: string;
  GalleryID?: string;
  [k: string]: unknown;
}
export interface Gallerytype1 {
  Value?: string;
  language?: boolean;
  [k: string]: unknown;
}
export interface ExperienceChildtype {
  Relationship: string;
  SequenceInfo?: ContentSequenceInfotype;
  ExperienceID: string;
  ALID: string;
  ExternalManifestID?: ExperienceChildtype1;
  [k: string]: unknown;
}
export interface ContentSequenceInfotype {
  Number?: number;
  DistributionNumber?: ComplexSequenceInfoDistributionNumber;
  HouseSequence?: ComplexSequenceInfoHouseSequence;
  /**
   * @minItems 0
   */
  AlternateNumber?: ComplexSequenceInfoAlternateNumber[];
  [k: string]: unknown;
}
export interface ComplexSequenceInfoDistributionNumber {
  Value?: string;
  domain?: string;
  [k: string]: unknown;
}
export interface ComplexSequenceInfoHouseSequence {
  Value?: string;
  domain?: string;
  [k: string]: unknown;
}
export interface ComplexSequenceInfoAlternateNumber {
  Value?: string;
  domain?: string;
  [k: string]: unknown;
}
export interface ExperienceChildtype1 {
  Value?: string;
  [k: string]: unknown;
}
export interface TimedEventSequenceListtype {
  /**
   * @minItems 1
   */
  TimedEventSequence: [TimedEventSequencetype, ...TimedEventSequencetype[]];
  [k: string]: unknown;
}
export interface TimedEventSequencetype {
  PresentationID: string;
  PlayableSequenceID: string;
  /**
   * @minItems 1
   */
  TimedEvent: [TimedEventtype, ...TimedEventtype[]];
  TimedSequenceID: string;
  [k: string]: unknown;
}
export interface TimedEventtype {
  StartTimecode: Timecodetype;
  EndTimecode: Timecodetype;
  Type: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  PresentationID: string;
  PlayableSequenceID: string;
  ExperienceID: string;
  PictureID: string;
  GalleryID: string;
  AppGroupID: string;
  AppID: string;
  /**
   * @minItems 1
   */
  TextGroupID: [TimedEventtype1, ...TimedEventtype1[]];
  URL: string;
  AdID: string;
  ISRC: string;
  ProductID: OtherIDtype;
  OtherID: OtherIDtype;
  TimePeriod: EventPeriodtype;
  Location: EventLocationtype;
  People: BasicMetadataPeopletype;
  UPC: string;
  Offset: number;
  TimecodeOffset: Timecodetype;
  Initialization: string;
  [k: string]: unknown;
}
export interface TimedEventtype1 {
  Value?: string;
  index?: number;
  [k: string]: unknown;
}
export interface EventPeriodtype {
  Type?: EventPeriodtype1;
  Name?: string;
  Start: string;
  End?: string;
  FictionalStart: EventPeriodtype2;
  FictionalEnd?: EventPeriodtype3;
  absolute?: boolean;
  [k: string]: unknown;
}
export interface EventPeriodtype1 {
  Value?: string;
  fictional?: boolean;
  [k: string]: unknown;
}
export interface EventPeriodtype2 {
  Value?: string;
  units?: string;
  [k: string]: unknown;
}
export interface EventPeriodtype3 {
  Value?: string;
  [k: string]: unknown;
}
export interface EventLocationtype {
  Type: EventLocationtype1;
  Name?: string;
  Address?:
    | string
    | number
    | number
    | boolean
    | null
    | {
        [k: string]: unknown;
      }
    | unknown[];
  EarthCoordinate?: EventLocationtypeEarthCoordinate;
  OtherCoordinates?: EventLocationtypeOtherCoordinates;
  [k: string]: unknown;
}
export interface EventLocationtype1 {
  fictional?: boolean;
  [k: string]: unknown;
}
export interface EventLocationEarthCoordinatetype {
  Latitude: number;
  Longitude: number;
  ElevationMeters?: number;
  [k: string]: unknown;
}
export interface EventLocationOtherCoordinatetype {
  /**
   * @minItems 1
   */
  Coordinate: [EventLocationOtherCoordinatetype1, ...EventLocationOtherCoordinatetype1[]];
  system: string;
  [k: string]: unknown;
}
export interface EventLocationOtherCoordinatetype1 {
  Value?: string;
  label: string;
  [k: string]: unknown;
}
export interface ALIDExperienceMapListtype {
  /**
   * @minItems 1
   */
  ALIDExperienceMap: [ALIDExperienceMaptype, ...ALIDExperienceMaptype[]];
  [k: string]: unknown;
}
export interface ALIDExperienceMaptype {
  /**
   * @minItems 1
   */
  ALID: [ALIDExperienceMaptype1, ...ALIDExperienceMaptype1[]];
  /**
   * @minItems 1
   */
  ExperienceID: [ALIDExperienceMaptype2, ...ALIDExperienceMaptype2[]];
  /**
   * @minItems 0
   */
  RelatedExperienceID?: ExperienceChildtype[];
  [k: string]: unknown;
}
export interface ALIDExperienceMaptype1 {
  Value?: string;
  deprecated?: boolean;
  [k: string]: unknown;
}
export interface ALIDExperienceMaptype2 {
  Value?: string;
  condition?: string;
  licenseType?: string;
  deprecated?: boolean;
  bonus?: boolean;
  [k: string]: unknown;
}
export interface DigitalAssetAncillaryDatatype {
  Type: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  BaseTrackID?: string;
  BaseTrackReference?: string;
  /**
   * @minItems 0
   */
  BaseTrackIdentifier?: ContentIdentifiertype[];
  TrackMetadata?: DigitalAssetMetadatatype;
  CombinedMetadata?: DigitalAssetMetadatatype;
  /**
   * @minItems 0
   */
  Compliance?: Compliancetype[];
  /**
   * @minItems 0
   */
  AssetIntent?: AssetIntenttype[];
  Private?: PrivateDatatype;
  [k: string]: unknown;
}
export interface DigitalAssetMetadatatype {
  Audio: DigitalAssetAudioDatatype;
  Video: DigitalAssetVideoDatatype;
  Subtitle: DigitalAssetSubtitleDatatype;
  Image: DigitalAssetImageDatatype;
  Interactive: DigitalAssetInteractiveDatatype;
  Ancillary: DigitalAssetAncillaryDatatype;
  [k: string]: unknown;
}
export interface InventoryMetadatatype {
  /**
   * @minItems 0
   */
  ContainerReference?: InventoryMetadatatypeContainerReference[];
  BasicMetadata?: BasicMetadatatype;
  /**
   * @minItems 0
   */
  Alias?: InventoryMetadataAliastype[];
  ContentID: string;
  [k: string]: unknown;
}
export interface BasicMetadatatype {
  UpdateNum?: number;
  /**
   * @minItems 1
   */
  LocalizedInfo: [BasicMetadataInfotype, ...BasicMetadataInfotype[]];
  RunLength?: string;
  ReleaseYear: unknown;
  ReleaseDate?: string;
  /**
   * @minItems 0
   */
  ReleaseHistory?: ReleaseHistorytype[];
  WorkType: string;
  /**
   * @minItems 0
   */
  WorkTypeDetail?: string[];
  PictureColorType?: ColorTypetype;
  PictureFormat?: string;
  ThreeD?: BasicMetadatatype1;
  AspectRatio?: BasicMetadatatype2;
  /**
   * @minItems 0
   */
  AltIdentifier?: ContentIdentifiertype[];
  RatingSet?: ContentRatingtype;
  /**
   * @minItems 0
   */
  People?: BasicMetadataPeopletype[];
  /**
   * @minItems 0
   */
  CountryOfOrigin?: BasicMetadatatypeCountryOfOrigin[];
  /**
   * @minItems 0
   */
  PrimarySpokenLanguage?: string[];
  /**
   * @minItems 0
   */
  OriginalLanguage?: string[];
  /**
   * @minItems 0
   */
  VersionLanguage?: string[];
  VersionIntent?: VersionIntenttype;
  /**
   * @minItems 0
   */
  AssociatedOrg?: AssociatedOrgtype[];
  /**
   * @minItems 0
   */
  ContentRelatedTo?: ContentRelatedTotype[];
  /**
   * @minItems 0
   */
  AncillaryDescription?: AncillaryDescriptiontype[];
  SequenceInfo?: ContentSequenceInfotype;
  /**
   * @minItems 0
   */
  Parent?: BasicMetadataParenttype[];
  ContentID: string;
  [k: string]: unknown;
}
export interface BasicMetadataInfotype {
  TitleDisplay19?: string;
  TitleDisplay60?: string;
  TitleDisplayUnlimited?: string;
  TitleSort?: string;
  /**
   * @minItems 0
   */
  ArtReference?: BasicMetadataInfotype1[];
  Summary190?: BasicMetadataInfotype2;
  Summary400?: BasicMetadataInfotype3;
  Summary4000?: BasicMetadataInfotype4;
  /**
   * @minItems 0
   */
  DisplayIndicators?: string[];
  /**
   * @minItems 0
   */
  Genre?: BasicMetadataInfotype5[];
  /**
   * @minItems 0
   */
  Keyword?: string[];
  VersionNotes?: string;
  /**
   * @minItems 1
   */
  Region: [Regiontype, ...Regiontype[]];
  /**
   * @minItems 1
   */
  ExcludedRegion: [Regiontype, ...Regiontype[]];
  /**
   * @minItems 0
   */
  TargetAudience?: Audiencetype[];
  OriginalTitle?: string;
  CopyrightLine?: string;
  /**
   * @minItems 0
   */
  PeopleLocal?: BasicMetadataPeopletype[];
  /**
   * @minItems 0
   */
  TitleAlternate?: BasicMetadataInfotype6[];
  language: string;
  _default?: boolean;
  condition?: string;
  [k: string]: unknown;
}
export interface BasicMetadataInfotype1 {
  Value?: string;
  resolution?: string;
  purpose?: string;
  [k: string]: unknown;
}
export interface BasicMetadataInfotype2 {
  Value?: string;
  cast?: boolean;
  [k: string]: unknown;
}
export interface BasicMetadataInfotype3 {
  Value?: string;
  cast?: boolean;
  [k: string]: unknown;
}
export interface BasicMetadataInfotype4 {
  Value?: string;
  cast?: boolean;
  [k: string]: unknown;
}
export interface BasicMetadataInfotype5 {
  Value?: string;
  source?: string;
  id?: string;
  level?: number;
  [k: string]: unknown;
}
export interface Audiencetype {
  Description?: string;
  /**
   * @minItems 0
   */
  Who?: string[];
  /**
   * @minItems 0
   */
  When?: Audiencetype1[];
  /**
   * @minItems 0
   */
  What?: Audiencetype2[];
  /**
   * @minItems 0
   */
  Identification?: ContentIdentifiertype[];
  /**
   * @minItems 0
   */
  Terms?: Termstype[];
  [k: string]: unknown;
}
export interface Audiencetype1 {
  Value?: string;
  startDate?: string;
  endDate?: string;
  [k: string]: unknown;
}
export interface Audiencetype2 {
  Value?: string;
  bonus?: boolean;
  condition?: string;
  [k: string]: unknown;
}
export interface BasicMetadataInfotype6 {
  Value?: string;
  type?: string;
  language?: string;
  [k: string]: unknown;
}
export interface ReleaseHistorytype {
  ReleaseType: ReleaseHistorytype1;
  /**
   * @minItems 0
   */
  DistrTerritory?: Regiontype[];
  Date: ReleaseHistorytype2;
  Description?: string;
  /**
   * @minItems 0
   */
  ReleaseOrg?: AssociatedOrgtype[];
  [k: string]: unknown;
}
export interface ReleaseHistorytype1 {
  Value?: string;
  wide?: boolean;
  [k: string]: unknown;
}
export interface ReleaseHistorytype2 {
  Value?: string;
  scheduled?: boolean;
  [k: string]: unknown;
}
export interface BasicMetadatatype1 {
  Value?: boolean;
  three60?: boolean;
  multiview?: boolean;
  [k: string]: unknown;
}
export interface BasicMetadatatype2 {
  Value?: string;
  original?: boolean;
  [k: string]: unknown;
}
export interface VersionIntenttype {
  Audience?: Audiencetype;
  /**
   * @minItems 0
   */
  Description?: VersionIntenttype1[];
  EditUse?: string;
  /**
   * @minItems 0
   */
  EditClass?: string[];
  MadeForRegion?: Regiontype;
  /**
   * @minItems 0
   */
  Terms?: Termstype[];
  [k: string]: unknown;
}
export interface VersionIntenttype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface ContentRelatedTotype {
  Relationship: ContentRelatedToRelationshiptype;
  /**
   * @minItems 0
   */
  Description?: ContentRelatedTotype1[];
  /**
   * @minItems 1
   */
  Work: [ContentRelatedToWorktype, ...ContentRelatedToWorktype[]];
  /**
   * @minItems 1
   */
  Character: [ContentRelatedToCharactertype, ...ContentRelatedToCharactertype[]];
  /**
   * @minItems 1
   */
  PersonOrGroup: [ContentRelatedToPersontype, ...ContentRelatedToPersontype[]];
  /**
   * @minItems 1
   */
  Period: [ContentRelatedToPeriodtype, ...ContentRelatedToPeriodtype[]];
  /**
   * @minItems 1
   */
  Place: [ContentRelatedToPlacetype, ...ContentRelatedToPlacetype[]];
  /**
   * @minItems 1
   */
  Event: [ContentRelatedToEventtype, ...ContentRelatedToEventtype[]];
  /**
   * @minItems 0
   */
  GroupingEntity?: GroupingEntitytype[];
  /**
   * @minItems 0
   */
  Terms?: Termstype[];
  [k: string]: unknown;
}
export interface ContentRelatedToRelationshiptype {
  Type: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  /**
   * @minItems 0
   */
  Description?: ContentRelatedToRelationshiptype1[];
  primary?: boolean;
  [k: string]: unknown;
}
export interface ContentRelatedToRelationshiptype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface ContentRelatedTotype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface ContentRelatedToWorktype {
  WorkType?: string;
  /**
   * @minItems 0
   */
  ContentID?: string[];
  /**
   * @minItems 0
   */
  OtherIdentifier?: ContentIdentifiertype[];
  /**
   * @minItems 0
   */
  Description?: ContentRelatedToWorktype1[];
  primary?: boolean;
  fictional?: boolean;
  [k: string]: unknown;
}
export interface ContentRelatedToWorktype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface ContentRelatedToCharactertype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface ContentRelatedToPersontype {
  /**
   * @minItems 0
   */
  Identifier?: PersonIdentifiertype[];
  Name: PersonNametype;
  /**
   * @minItems 0
   */
  Description?: ContentRelatedToPersontype1[];
  primary?: boolean;
  fictional?: boolean;
  [k: string]: unknown;
}
export interface ContentRelatedToPersontype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface ContentRelatedToPeriodtype {
  Date: ContentRelatedToPeriodtype1;
  Duration?: ContentRelatedToPeriodtype2;
  /**
   * @minItems 0
   */
  Description?: ContentRelatedToPeriodtype3[];
  primary?: boolean;
  fictional?: boolean;
  [k: string]: unknown;
}
export interface ContentRelatedToPeriodtype1 {
  Value?: string;
  approximate?: boolean;
  [k: string]: unknown;
}
export interface ContentRelatedToPeriodtype2 {
  Value?: string;
  approximate?: boolean;
  [k: string]: unknown;
}
export interface ContentRelatedToPeriodtype3 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface ContentRelatedToPlacetype {
  Region?: Regiontype;
  Address?: string;
  EarthCoordinate?: CoordinateEarthtype;
  OtherCoordinate?: CoordinateOthertype;
  /**
   * @minItems 0
   */
  Description?: ContentRelatedToPlacetype1[];
  primary?: boolean;
  fictional?: boolean;
  [k: string]: unknown;
}
export interface CoordinateEarthtype {
  Latitude: number;
  Longitude: number;
  ElevationMeters?: number;
  [k: string]: unknown;
}
export interface CoordinateOthertype {
  /**
   * @minItems 1
   */
  Coordinate: [CoordinateOthertype1, ...CoordinateOthertype1[]];
  system: string;
  [k: string]: unknown;
}
export interface CoordinateOthertype1 {
  Value?: string;
  label: string;
  [k: string]: unknown;
}
export interface ContentRelatedToPlacetype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface ContentRelatedToEventtype {
  Type?: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  Date?: ContentRelatedToEventtype1;
  Duration?: ContentRelatedToEventtype2;
  /**
   * @minItems 0
   */
  Description?: ContentRelatedToEventtype3[];
  primary?: boolean;
  fictional?: boolean;
  [k: string]: unknown;
}
export interface ContentRelatedToEventtype1 {
  Value?: string;
  approximate?: boolean;
  [k: string]: unknown;
}
export interface ContentRelatedToEventtype2 {
  Value?: string;
  approximate?: boolean;
  [k: string]: unknown;
}
export interface ContentRelatedToEventtype3 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface AncillaryDescriptiontype {
  Type: string;
  /**
   * @minItems 0
   */
  SubType?: string[];
  /**
   * @minItems 1
   */
  Description: [AncillaryDescriptiontype1, ...AncillaryDescriptiontype1[]];
  /**
   * @minItems 0
   */
  AdditionalTerms?: Termstype[];
  ancillaryDescriptionID?: string;
  [k: string]: unknown;
}
export interface AncillaryDescriptiontype1 {
  Value?: string;
  language?: string;
  [k: string]: unknown;
}
export interface BasicMetadataParenttype {
  ParentContentID: string;
  Parent: BasicMetadatatype;
  SequenceInfo?: ContentSequenceInfotype;
  /**
   * @minItems 1
   */
  Region: [Regiontype, ...Regiontype[]];
  /**
   * @minItems 1
   */
  ExcludedRegion: [Regiontype, ...Regiontype[]];
  relationshipType?:
    | "isclipof"
    | "isepisodeof"
    | "isseasonof"
    | "ispieceof"
    | "ispartof"
    | "isderivedfrom"
    | "iscompositeof"
    | "issupplementto"
    | "ispromotionfor"
    | "isabsedon"
    | "isdescendentof";
  [k: string]: unknown;
}
export interface InventoryMetadataAliastype {
  /**
   * @minItems 0
   */
  LocalizedPair?: InventoryMetadataLocalizedPairtype[];
  ContentID: string;
  [k: string]: unknown;
}
export interface InventoryMetadataLocalizedPairtype {
  LanguageIncluded: string;
  RegionIncluded?: Regiontype;
  [k: string]: unknown;
}
export interface InventoryTextObjecttype {
  /**
   * @minItems 1
   */
  ContainerReference: [InventoryTextObjecttypeContainerReference, ...InventoryTextObjecttypeContainerReference[]];
  SubtitleID: InventoryTextObjecttype1;
  /**
   * @minItems 1
   */
  TextString: [InventoryTextObjecttype2, ...InventoryTextObjecttype2[]];
  TextObjectID: string;
  language?: string;
  [k: string]: unknown;
}
export interface InventoryTextObjecttype1 {
  Value?: string;
  time?: string;
  [k: string]: unknown;
}
export interface InventoryTextObjecttype2 {
  Value?: string;
  index?: number;
  [k: string]: unknown;
}
export interface InventoryManifesttype {
  ContainerReference: InventoryManifesttypeContainerReference;
  ManifestID: string;
  [k: string]: unknown;
}
export interface PresentationManifesttype {
  Inventory: Inventorytype;
  Presentation: Presentationtype;
  PictureGroups?: PictureGroupListtype;
  TextGroups?: TextGroupListtype;
  TimedEventSequences?: TimedEventSequenceListtype;
  updateNum?: number;
  workflow?: string;
  updateDeliveryType?: string;
  versionDescription?: string;
  timestamp?: string;
  [k: string]: unknown;
}
export interface MediaManifestEdittype {
  Source?: ManifestSourcetype;
  DeleteObjects?: MediaManifestEditDeletetype;
  AddObjects?: MediaManifestEditAddtype;
  Description?: string;
  Instructions?: string;
  type?: string;
  reference?: string;
  ManifestID?: string;
  ExtraVersionReference?: string;
  updateNum?: number;
  workflow?: string;
  updateDeliveryType?: string;
  versionDescription?: string;
  timestamp?: string;
  [k: string]: unknown;
}
export interface MediaManifestEditDeletetype {
  /**
   * @minItems 0
   */
  AudioTrackID?: string[];
  /**
   * @minItems 0
   */
  VideoTrackID?: string[];
  /**
   * @minItems 0
   */
  SubtitleTrackID?: string[];
  /**
   * @minItems 0
   */
  ImageID?: string[];
  /**
   * @minItems 0
   */
  InteractiveTrackID?: string[];
  /**
   * @minItems 0
   */
  TextObjectID?: string[];
  /**
   * @minItems 0
   */
  PlayableSequenceID?: string[];
  /**
   * @minItems 0
   */
  PresentationID?: string[];
  /**
   * @minItems 0
   */
  PictureID?: string[];
  /**
   * @minItems 0
   */
  GalleryID?: string[];
  /**
   * @minItems 0
   */
  AppGroupID?: string[];
  /**
   * @minItems 0
   */
  TextGroupID?: string[];
  /**
   * @minItems 0
   */
  TimedSequenceID?: string[];
  /**
   * @minItems 0
   */
  ExperienceID?: string[];
  /**
   * @minItems 0
   */
  ALIDExperienceMap?: ALIDExperienceMaptype[];
  /**
   * @minItems 0
   */
  ContentID?: string[];
  /**
   * @minItems 0
   */
  LocalizedInfoRef?: MediaManifestEditLocReftype[];
  [k: string]: unknown;
}
export interface MediaManifestEditLocReftype {
  ContentID: string;
  Language: string;
  Region?: Regiontype;
  [k: string]: unknown;
}
export interface MediaManifestEditAddtype {
  Compatibility?: Compatibilitytype;
  Inventory?: Inventorytype;
  Presentations?: PresentationListtype;
  PlayableSequences?: PlayableSequenceListtype;
  PictureGroups?: PictureGroupListtype;
  AppGroups?: AppGroupListtype;
  /**
   * @minItems 0
   */
  Metadata?: InventoryMetadatatype[];
  /**
   * @minItems 0
   */
  TextObject?: string[];
  /**
   * @minItems 0
   */
  TextGroup?: TextGrouptype[];
  /**
   * @minItems 0
   */
  TextGroups?: TextGroupListtype[];
  /**
   * @minItems 0
   */
  TimedEventSequence?: TimedEventSequencetype[];
  Experiences?: ExperienceListtype;
  ALIDExperienceMaps?: ALIDExperienceMapListtype;
  [k: string]: unknown;
}
